// Manual analysis data - generated by Claude directly
const fs = require("fs");
const path = require("path");

const DATA_PATH = path.join(__dirname, "..", "data", "articles.json");

const analyses = {
  "https://claude.com/blog/claude-managed-agents": {
    summary: "Anthropic이 출시한 Claude Managed Agents는 프로덕션급 AI 에이전트를 10배 빠르게 배포할 수 있는 API 모음입니다. 샌드박스 실행, 멀티에이전트 조율, 거버넌스 기능을 자동 처리하며, Notion, Rakuten, Asana, Sentry 등이 이미 활용 중입니다.",
    keyFeatures: [
      "프로덕션급 인프라 - 샌드박스, 인증, 도구 관리 자동 처리",
      "장시간 세션 - 수 시간 자율 작동, 연결 끊겨도 진행 상황 유지",
      "멀티에이전트 조율 - 여러 에이전트가 병렬로 복잡한 작업 처리",
      "통제된 거버넌스 - 권한 관리, 신원 확인, 실행 추적 내장",
      "자동 자체 평가 - 성공 기준 대비 반복 개선으로 최대 10포인트 성공률 향상"
    ],
    howToUse: "Claude Platform에서 API를 통해 에이전트의 작업, 도구, 가드레일을 정의하면 Anthropic 인프라에서 실행됩니다. 콘솔에서 모든 도구 호출과 실패 모드를 검사할 수 있으며, 현재 공개 베타로 이용 가능합니다.",
    useCases: [
      "코드베이스를 읽고 수정 계획을 세운 뒤 PR을 여는 코딩 에이전트",
      "Slack/Teams에서 직접 작업을 할당받아 문서, 스프레드시트를 생성하는 업무 에이전트",
      "버그 감지에서 패치 작성, PR 제출까지 자동 처리하는 디버깅 에이전트",
      "여러 팀에 걸친 복잡한 프로젝트를 병렬로 처리하는 멀티에이전트 파이프라인"
    ],
    tags: ["에이전트", "프로덕션 배포", "멀티에이전트", "API", "자동화"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/harnessing-claudes-intelligence": {
    summary: "Claude 앱을 만들 때 지능, 지연시간, 비용의 균형을 맞추는 3가지 핵심 패턴을 소개합니다. Claude가 이미 아는 것을 활용하고, 불필요한 것을 제거하며, 경계를 신중히 설정하는 것이 핵심입니다.",
    keyFeatures: [
      "범용 도구(Bash, 텍스트 편집기)만으로 SWE-bench 49% 달성",
      "코드 실행 도구로 Claude가 직접 데이터 필터링하여 토큰 비용 절감",
      "Skills로 점진적 정보 공개 - 필요할 때만 상세 지침 로드",
      "메모리 폴더로 컨텍스트 파일 저장 (정확도 60.4% → 67.2% 향상)",
      "캐시된 토큰은 기본 입력의 10% 비용으로 비용 최적화"
    ],
    howToUse: "시스템 프롬프트에 모든 지침을 넣지 말고 Skills로 분리하세요. Claude에게 코드 실행 도구를 주어 직접 데이터를 필터링하게 하고, 서브에이전트로 독립 작업을 격리하세요. 정적 콘텐츠를 프롬프트 앞에 배치해 캐시 히트율을 높이세요.",
    useCases: [
      "토큰 비용을 줄이고 싶을 때 - 컨텍스트 관리 패턴 적용",
      "다양한 종류의 작업을 하나의 에이전트로 처리할 때 - Skills로 동적 컨텍스트 로딩",
      "장기 실행 에이전트 구축 시 - 메모리 폴더와 컴팩션 활용",
      "여러 모델/작업 간 비용 최적화가 필요할 때 - 캐시 전략 적용"
    ],
    tags: ["컨텍스트 관리", "비용 최적화", "Skills", "메모리", "에이전트 패턴"],
    difficulty: "고급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/claude-builds-visuals": {
    summary: "Claude가 대화 중 인터랙티브 차트, 다이어그램, 시각화를 인라인으로 직접 생성합니다. Artifacts와 달리 대화 흐름 속에서 이해를 돕기 위한 임시 시각 요소이며, 모든 플랜에서 사용 가능합니다.",
    keyFeatures: [
      "대화 중 인라인 차트, 다이어그램, 시각화 자동 생성",
      "인터랙티브 - 클릭하고 조작할 수 있는 시각화",
      "Claude가 자동 판단하여 시각화를 생성하거나 직접 요청 가능",
      "생성 후 조정 요청으로 수정 가능"
    ],
    howToUse: "Claude 채팅에서 '이걸 다이어그램으로 그려줘', '시간에 따른 변화를 시각화해줘' 같은 요청을 하면 됩니다. 기본적으로 켜져 있으며, Claude가 필요하다고 판단하면 자동으로 시각화를 생성합니다.",
    useCases: [
      "복리 이자 같은 수학적 개념을 시각적으로 이해하고 싶을 때",
      "주기율표 등 복잡한 데이터를 인터랙티브하게 탐색할 때",
      "데이터 분석 결과를 즉시 차트로 확인하고 싶을 때"
    ],
    tags: ["시각화", "차트", "다이어그램", "인터랙티브"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/how-enterprises-are-building-ai-agents-in-2026": {
    summary: "500명 이상의 기술 리더 설문 결과, 57%의 조직이 멀티 스테이지 워크플로우에 에이전트를 배포 중이며, 80%가 측정 가능한 경제적 수익을 보고했습니다. 코딩이 도입을 이끌고 있으며, 2026년에는 더 복잡한 유스케이스로 확대됩니다.",
    keyFeatures: [
      "57%가 멀티 스테이지 워크플로우에 에이전트 배포 중",
      "90% 조직이 개발에 AI 활용, 86%가 프로덕션 코드에 에이전트 사용",
      "80%가 AI 에이전트 투자에서 측정 가능한 수익 달성",
      "2026년 81%가 더 복잡한 유스케이스 계획"
    ],
    howToUse: "코딩/개발 분야부터 시작하여 AI 에이전트를 도입하고, 이후 데이터 분석, 내부 프로세스 자동화로 확대하세요. 기존 시스템과의 통합, 데이터 품질, 변화 관리를 주요 과제로 준비하세요.",
    useCases: [
      "코드 생성, 리뷰, 테스트 자동화로 개발 생산성 향상",
      "데이터 분석 및 리포트 자동 생성",
      "내부 프로세스 자동화 - 문서 처리, 고객 서비스",
      "크로스 펑셔널 프로젝트에 에이전트 배포"
    ],
    tags: ["엔터프라이즈", "에이전트 도입", "통계", "트렌드"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/improving-frontend-design-through-skills": {
    summary: "AI가 생성하는 프론트엔드가 'AI 슬롭'처럼 보이는 문제를 Skills로 해결합니다. ~400 토큰의 프론트엔드 디자인 스킬을 만들어 타이포그래피, 색상, 애니메이션, 배경을 개선하면, 컨텍스트 오버헤드 없이 훨씬 나은 UI를 생성할 수 있습니다.",
    keyFeatures: [
      "분포 수렴(distributional convergence) 문제 해결 - AI의 '안전한 디자인' 기본값 탈피",
      "Skills로 동적 컨텍스트 로딩 - 필요할 때만 디자인 지침 로드",
      "~400 토큰 컴팩트 프롬프트로 타이포그래피, 색상, 모션, 배경 전면 개선",
      "테마 기반 프롬프팅 - RPG, 미니멀 등 특정 미학 적용 가능"
    ],
    howToUse: "Claude Code의 .claude/skills/ 폴더에 프론트엔드 디자인 스킬 파일을 만들고, 타이포그래피(Inter/Roboto 금지, 대비 높은 폰트 조합), 테마, 애니메이션, 배경에 대한 지침을 작성하세요. Claude가 프론트엔드 작업을 할 때 자동으로 이 스킬을 참조합니다.",
    useCases: [
      "AI로 프론트엔드를 생성할 때 '뻔한 AI 디자인'을 피하고 싶을 때",
      "브랜드 아이덴티티에 맞는 UI를 일관되게 생성할 때",
      "여러 프로젝트에서 동일한 디자인 기준을 재사용할 때",
      "프로토타이핑 시 즉시 세련된 UI를 만들고 싶을 때"
    ],
    tags: ["Skills", "프론트엔드", "디자인", "타이포그래피", "프롬프팅"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/building-ai-agents-in-financial-services": {
    summary: "금융 서비스에서 AI 에이전트 구축 가이드. NBIM, Brex, Intuit TurboTax 등의 실제 사례와 함께 레거시 시스템 통합, 규제 준수, 리스크 관리 등 금융 특유의 도전과제를 다룹니다.",
    keyFeatures: [
      "사기 탐지에서 200-2000% 생산성 향상 가능 (McKinsey 리서치)",
      "NBIM 직원들이 매주 수백 시간 절약",
      "Brex가 100% 거래를 AI로 이상 탐지",
      "레거시 시스템 통합, 규제 복잡성, 실시간 리스크 관리 가이드"
    ],
    howToUse: "현대적 API가 있는 플랫폼부터 에이전트를 연동하고, 레거시 시스템은 미들웨어로 연결하세요. 고객 서비스부터 시작하여 사기 탐지, 팀 역량 강화로 확대하는 것이 좋습니다.",
    useCases: [
      "고객 서비스 자동화 - 잔액 조회, 카드 교체 등 루틴 업무 처리",
      "사기 탐지 - 실시간 거래 모니터링 및 패턴 감지",
      "규제 문서 분석 및 컴플라이언스 자동화",
      "자연어로 재무 데이터 조회 및 분석"
    ],
    tags: ["금융", "에이전트", "사기 탐지", "규제 준수", "엔터프라이즈"],
    difficulty: "고급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/claude-code-on-the-web": {
    summary: "Claude Code를 웹에서 사용할 수 있게 되었습니다. GitHub 저장소를 연결해 여러 코딩 작업을 동시에 실행하고, 실시간으로 진행 상황을 추적하며, 자동으로 PR을 생성합니다. iOS 앱에서도 탐색 가능합니다.",
    keyFeatures: [
      "클라우드 기반 코딩 작업 위임 - Anthropic 인프라에서 실행",
      "여러 저장소에서 동시에 여러 작업 병렬 처리",
      "실시간 진행 상황 추적 및 자동 PR 생성",
      "독립된 샌드박스 환경 (네트워크/파일 시스템 제한)",
      "iOS 앱에서 코딩 작업 탐색 미리보기"
    ],
    howToUse: "claude.ai/code에서 GitHub 저장소를 연결하고, 작업을 자연어로 설명하면 Claude가 코드를 작성하고 PR을 생성합니다. 여러 작업을 동시에 할당할 수 있으며, Pro/Max 사용자 베타로 이용 가능합니다.",
    useCases: [
      "버그 수정 및 정기 유지보수 작업을 병렬로 위임",
      "테스트 코드 작성을 자동화",
      "프로젝트 구조나 코드베이스에 대한 질문에 답변",
      "이동 중 모바일에서 코딩 작업 현황 확인"
    ],
    tags: ["웹 코딩", "병렬 작업", "자동 PR", "GitHub", "클라우드"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/claude-and-slack": {
    summary: "Claude와 Slack의 통합으로 팀 커뮤니케이션 도구에서 직접 AI를 활용할 수 있습니다. Slack 채널에서 Claude를 멘션하여 질문, 요약, 분석 등의 작업을 수행합니다.",
    keyFeatures: [
      "Slack 채널에서 @Claude로 직접 호출",
      "대화 맥락을 이해하고 관련 답변 제공",
      "팀 전체가 하나의 AI 도구를 공유",
      "기존 워크플로우에 자연스럽게 통합"
    ],
    howToUse: "Slack 앱 디렉토리에서 Claude를 설치하고, 채널이나 DM에서 @Claude를 멘션하여 질문하면 됩니다. 채널의 대화 맥락을 파악하여 관련 답변을 제공합니다.",
    useCases: [
      "팀 미팅 노트 요약 및 액션 아이템 추출",
      "채널의 긴 대화를 빠르게 요약하고 핵심 파악",
      "기술적 질문에 대한 즉석 답변",
      "문서 초안 작성 및 리뷰 요청"
    ],
    tags: ["Slack", "팀 협업", "통합", "커뮤니케이션"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/claude-for-chrome": {
    summary: "Chrome 브라우저에서 Claude를 직접 사용할 수 있는 확장 프로그램의 파일럿 출시. 웹 브라우징 중 페이지 내용을 기반으로 질문, 요약, 분석이 가능합니다.",
    keyFeatures: [
      "Chrome 브라우저에서 직접 Claude 호출",
      "현재 보고 있는 웹 페이지 내용 기반 질문/분석",
      "사이드 패널에서 대화하며 웹 브라우징 병행",
      "텍스트 선택 후 바로 분석 요청 가능"
    ],
    howToUse: "Chrome 웹 스토어에서 Claude 확장 프로그램을 설치하세요. 웹 페이지를 보면서 사이드 패널을 열어 해당 페이지에 대한 질문을 하거나, 텍스트를 선택해 요약/번역/분석을 요청할 수 있습니다.",
    useCases: [
      "긴 기사나 논문을 빠르게 요약할 때",
      "외국어 웹 페이지를 이해해야 할 때",
      "리서치 중 여러 페이지의 정보를 비교 분석할 때",
      "코드 문서를 읽으며 실시간으로 질문할 때"
    ],
    tags: ["Chrome", "브라우저", "확장 프로그램", "웹 분석"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/how-anthropic-teams-use-claude-code": {
    summary: "Anthropic 내부 팀들이 Claude Code를 실제로 활용하는 사례 모음. 개발자뿐 아니라 마케팅, 법무팀도 활용하며, 코드베이스 이해, 테스트 자동화, 디버깅 3배 가속, Figma→React 변환 등 다양한 사례를 다룹니다.",
    keyFeatures: [
      "신입 개발자가 코드베이스를 빠르게 파악하여 온보딩 가속",
      "포괄적 단위 테스트 자동 작성 및 GitHub Actions 통합",
      "디버깅 시간 3배 단축 - 스택 트레이스 자동 분석",
      "Figma 디자인에서 React 앱 자동 생성",
      "마케팅팀의 CSV 처리 및 수백 개 광고 변형 생성"
    ],
    howToUse: "터미널에서 Claude Code를 실행하고 자연어로 작업을 설명하세요. 코드베이스를 분석해달라, 이 함수의 테스트를 작성해달라, 이 에러를 디버깅해달라 등 구체적으로 요청하면 됩니다. 비개발자도 문제를 설명하면 솔루션을 구축합니다.",
    useCases: [
      "새 프로젝트에 합류했을 때 코드베이스 빠르게 이해",
      "기존 코드에 대한 테스트 코드 자동 작성",
      "프로덕션 에러를 스택 트레이스로 빠르게 디버깅",
      "비개발자가 데이터 처리 자동화 도구를 직접 만들 때"
    ],
    tags: ["Claude Code", "테스트", "디버깅", "프로토타이핑", "비개발자"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/carta-healthcare-clinical-abstractor": {
    summary: "Carta Healthcare가 Claude를 활용해 임상 추상화(clinical abstraction) AI를 구축한 사례. 의료 문서에서 핵심 데이터를 추출하고 임상 전문가처럼 추론하는 시스템을 개발했습니다.",
    keyFeatures: [
      "의료 문서에서 구조화된 데이터 자동 추출",
      "임상 추상화 전문가 수준의 추론 능력",
      "복잡한 의료 기록의 맥락적 이해",
      "대량 문서 처리 자동화"
    ],
    howToUse: "Claude API를 활용해 의료 문서를 입력하고, 도메인별 프롬프트를 설계하여 필요한 임상 데이터를 추출합니다. 전문가 검증 루프를 포함하여 정확도를 보장하세요.",
    useCases: [
      "의료 기록에서 핵심 임상 데이터 추출 자동화",
      "대량의 비정형 의료 문서를 구조화된 데이터로 변환",
      "임상 연구를 위한 데이터 수집 및 분류",
      "의료 품질 보고를 위한 문서 분석"
    ],
    tags: ["헬스케어", "임상 데이터", "문서 분석", "자동화"],
    difficulty: "고급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/subagents-in-claude-code": {
    summary: "Claude Code에서 서브에이전트를 언제, 어떻게 사용하는지에 대한 가이드. 독립된 컨텍스트 윈도우에서 작업을 격리하여 메인 컨텍스트를 보호하고, 복잡한 작업을 병렬로 처리하는 방법을 설명합니다.",
    keyFeatures: [
      "독립된 컨텍스트 윈도우에서 작업 격리",
      "메인 컨텍스트 윈도우 보호 - 불필요한 정보 유입 방지",
      "복잡한 작업의 병렬 처리",
      "BrowseComp에서 단일 에이전트 대비 2.8% 성능 향상"
    ],
    howToUse: "Claude Code에서 복잡한 작업을 할 때, 독립적으로 처리 가능한 하위 작업을 서브에이전트에 위임하세요. 코드 검색, 파일 분석 등 결과만 필요한 작업을 서브에이전트로 분리하면 메인 컨텍스트가 깔끔하게 유지됩니다.",
    useCases: [
      "여러 파일을 동시에 분석해야 할 때 - 각각 서브에이전트로 위임",
      "대규모 코드베이스에서 관련 코드를 검색할 때",
      "메인 작업과 독립적인 조사/리서치가 필요할 때",
      "테스트 실행, 린트 체크 등을 병렬로 처리할 때"
    ],
    tags: ["서브에이전트", "병렬 처리", "컨텍스트 관리", "Claude Code"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/claude-platform-compliance-api": {
    summary: "Claude Platform 활동을 감사할 수 있는 Compliance API 출시. 조직의 Claude 사용 내역을 추적하고, 규제 요구사항에 맞는 감사 로그를 생성합니다.",
    keyFeatures: [
      "Claude Platform 활동에 대한 완전한 감사 로그",
      "조직 전체 사용 내역 추적",
      "규제 컴플라이언스 요구사항 충족",
      "API 기반 프로그래밍 방식 접근"
    ],
    howToUse: "Compliance API를 호출하여 조직의 Claude 사용 로그를 조회합니다. 기간별, 사용자별, 활동 유형별 필터링이 가능하며, 기존 감사 시스템과 통합할 수 있습니다.",
    useCases: [
      "금융/의료 등 규제 산업에서 AI 사용 내역 감사",
      "조직의 AI 사용 정책 준수 여부 모니터링",
      "보안 사고 발생 시 활동 추적 및 조사",
      "경영진 대상 AI 사용 리포트 자동 생성"
    ],
    tags: ["컴플라이언스", "감사", "API", "보안", "엔터프라이즈"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/auto-mode": {
    summary: "Claude Code에 Auto 모드가 추가되어 사용자 확인 없이 자율적으로 작업을 수행합니다. 파일 편집, 명령 실행 등을 연속으로 처리하여 작업 흐름이 끊기지 않습니다.",
    keyFeatures: [
      "사용자 확인 없이 자율적 작업 수행",
      "파일 편집, 명령 실행 연속 처리",
      "작업 흐름 중단 없는 매끄러운 경험",
      "필요시 수동 모드로 전환 가능"
    ],
    howToUse: "Claude Code에서 /auto-mode를 활성화하면, Claude가 도구 실행에 대해 일일이 확인을 구하지 않고 자율적으로 작업합니다. 복잡한 작업을 맡길 때 특히 유용하며, 신뢰할 수 있는 작업에서 사용하세요.",
    useCases: [
      "여러 파일에 걸친 리팩토링을 한 번에 처리할 때",
      "테스트 작성 → 실행 → 수정 사이클을 자동으로 반복할 때",
      "보일러플레이트 코드를 빠르게 생성할 때",
      "코드베이스 전체에 일괄 변경을 적용할 때"
    ],
    tags: ["Auto 모드", "자율 실행", "Claude Code", "생산성"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/dispatch-and-computer-use": {
    summary: "Claude의 Computer Use 기능으로 컴퓨터에서 직접 작업을 수행합니다. 화면을 보고, 클릭하고, 타이핑하여 실제 애플리케이션을 조작할 수 있습니다.",
    keyFeatures: [
      "컴퓨터 화면을 직접 보고 이해",
      "마우스 클릭, 키보드 입력으로 앱 조작",
      "여러 애플리케이션에 걸친 작업 자동화",
      "사람이 하는 것처럼 GUI 기반 작업 수행"
    ],
    howToUse: "Claude에 Computer Use를 활성화하고 작업을 설명하면, Claude가 화면을 보면서 직접 앱을 조작합니다. 브라우저, 스프레드시트, 디자인 도구 등 GUI 기반 작업에 적합합니다.",
    useCases: [
      "웹 앱에서 반복적인 데이터 입력 자동화",
      "여러 앱 간 데이터를 복사/붙여넣기하는 워크플로우",
      "GUI 기반 소프트웨어 테스트 자동화",
      "스크린샷을 보고 UI 문제를 파악하고 수정"
    ],
    tags: ["Computer Use", "GUI 자동화", "화면 인식", "데스크톱"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/product-management-on-the-ai-exponential": {
    summary: "AI 시대의 프로덕트 매니지먼트에 대한 고찰. AI의 기하급수적 발전 속에서 PM이 어떻게 제품을 기획하고, AI 기능을 제품에 통합해야 하는지를 논의합니다.",
    keyFeatures: [
      "AI 역량의 기하급수적 성장에 맞춘 PM 전략",
      "AI를 제품에 통합할 때의 사고 프레임워크",
      "빠르게 변하는 AI 환경에서의 제품 로드맵 설계",
      "AI 기능의 사용자 경험 설계 원칙"
    ],
    howToUse: "AI 제품을 기획할 때 이 글의 프레임워크를 참고하세요. AI 역량이 급변하므로 고정된 로드맵보다 적응적 접근이 중요합니다. 현재 AI가 못 하는 것에 기반한 설계는 빠르게 무효화될 수 있음을 인지하세요.",
    useCases: [
      "AI 기능을 제품에 도입하려는 PM",
      "AI 기반 스타트업의 제품 전략 수립",
      "기존 제품에 AI 에이전트를 통합할 때의 UX 설계",
      "AI 역량 변화에 따른 로드맵 조정"
    ],
    tags: ["프로덕트 매니지먼트", "AI 전략", "제품 기획"],
    difficulty: "중급",
    toolRecommendation: "둘 다"
  },
  "https://claude.com/blog/code-with-claude-san-francisco-london-tokyo": {
    summary: "Code with Claude 이벤트가 샌프란시스코, 런던, 도쿄에서 개최됩니다. 개발자들이 Claude Code의 최신 기능을 체험하고, 베스트 프랙티스를 배우는 행사입니다.",
    keyFeatures: [
      "3개 도시 동시 개최 - SF, 런던, 도쿄",
      "Claude Code 최신 기능 라이브 데모",
      "개발자 커뮤니티 네트워킹",
      "실전 워크샵 및 핸즈온 세션"
    ],
    howToUse: "이벤트 페이지에서 참가 신청하세요. 직접 참석이 어려우면 온라인 세션이나 이후 공개되는 녹화 영상을 확인하세요.",
    useCases: [
      "Claude Code의 최신 기능을 빠르게 배우고 싶을 때",
      "다른 개발자들의 활용 사례를 듣고 싶을 때",
      "Anthropic 팀에 직접 질문하고 싶을 때"
    ],
    tags: ["이벤트", "커뮤니티", "워크샵"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/1m-context-ga": {
    summary: "Opus 4.6과 Sonnet 4.6에서 1M(백만) 토큰 컨텍스트 윈도우가 정식 출시되었습니다. 대규모 코드베이스, 긴 문서, 복잡한 데이터를 한 번에 처리할 수 있습니다.",
    keyFeatures: [
      "1M 토큰 컨텍스트 윈도우 정식 지원 (GA)",
      "Opus 4.6, Sonnet 4.6 모두 지원",
      "대규모 코드베이스 전체를 한 번에 분석 가능",
      "긴 문서, 대량 데이터 세트 처리"
    ],
    howToUse: "API 호출 시 긴 입력을 보내면 자동으로 1M 컨텍스트를 활용합니다. 대규모 코드베이스 분석, 긴 법률 문서 리뷰, 대량 데이터 분석 등에 활용하세요. 캐시와 함께 사용하면 비용 효율적입니다.",
    useCases: [
      "수만 줄의 코드베이스를 한 번에 분석하여 아키텍처 파악",
      "긴 법률/의료 문서를 통째로 분석하고 핵심 추출",
      "여러 파일에 걸친 코드 리팩토링을 컨텍스트 유지하며 수행",
      "대량의 로그 데이터를 한 번에 분석하여 패턴 발견"
    ],
    tags: ["1M 컨텍스트", "대규모 분석", "Opus 4.6", "Sonnet 4.6"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/claude-excel-powerpoint-updates": {
    summary: "Claude의 Excel과 PowerPoint 지원이 강화되었습니다. 스프레드시트 데이터 분석, 차트 생성, 프레젠테이션 자동 생성 등 오피스 도구와의 통합이 개선되었습니다.",
    keyFeatures: [
      "Excel 파일 직접 업로드 및 분석",
      "데이터 기반 차트와 시각화 자동 생성",
      "PowerPoint 프레젠테이션 자동 생성",
      "복잡한 스프레드시트 수식 작성 지원"
    ],
    howToUse: "Claude에 Excel 파일을 업로드하고 분석을 요청하세요. '이 데이터로 매출 트렌드 차트를 만들어줘', '이 데이터를 요약한 프레젠테이션을 만들어줘' 같은 요청이 가능합니다.",
    useCases: [
      "매출/재무 데이터를 빠르게 분석하고 인사이트 도출",
      "미팅용 프레젠테이션을 데이터 기반으로 자동 생성",
      "복잡한 Excel 수식을 자연어로 설명하고 작성",
      "여러 시트의 데이터를 통합 분석하여 리포트 생성"
    ],
    tags: ["Excel", "PowerPoint", "데이터 분석", "오피스"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/code-review": {
    summary: "Claude Code에 코드 리뷰 기능이 추가되었습니다. PR의 변경사항을 분석하고, 버그, 보안 취약점, 성능 문제를 자동으로 감지하여 리뷰 코멘트를 작성합니다.",
    keyFeatures: [
      "PR 변경사항 자동 분석 및 리뷰",
      "버그, 보안 취약점, 성능 문제 자동 감지",
      "구체적인 개선 제안과 코드 예시 제공",
      "GitHub PR에 직접 코멘트 작성"
    ],
    howToUse: "Claude Code에서 PR 리뷰를 요청하면, 변경된 파일을 분석하고 이슈를 발견하여 코멘트를 작성합니다. GitHub Actions와 연동하면 PR이 생성될 때마다 자동으로 리뷰를 수행할 수 있습니다.",
    useCases: [
      "팀의 코드 리뷰 프로세스 가속화",
      "보안 취약점의 조기 발견",
      "코딩 표준 준수 여부 자동 체크",
      "주니어 개발자의 코드 품질 향상 지원"
    ],
    tags: ["코드 리뷰", "PR 자동화", "보안", "Claude Code"],
    difficulty: "초급",
    toolRecommendation: "Claude"
  },
  "https://claude.com/blog/common-workflow-patterns-for-ai-agents-and-when-to-use-them": {
    summary: "AI 에이전트의 일반적인 워크플로우 패턴과 각 패턴을 언제 사용해야 하는지 가이드. 단순 체인에서 멀티에이전트 조율까지 다양한 패턴을 비교 분석합니다.",
    keyFeatures: [
      "프롬프트 체이닝, 라우팅, 병렬화 등 핵심 패턴 정리",
      "각 패턴의 장단점 및 적합한 상황 가이드",
      "단순 패턴부터 복잡한 멀티에이전트 조율까지 스펙트럼 제시",
      "실무 적용 시 고려사항과 트레이드오프 분석"
    ],
    howToUse: "에이전트를 구축하기 전에 이 가이드를 참고하여 적합한 패턴을 선택하세요. 가능한 단순한 패턴부터 시작하고, 필요에 따라 복잡도를 높이는 것이 좋습니다. 각 패턴의 트레이드오프를 이해하고 선택하세요.",
    useCases: [
      "새로운 AI 에이전트를 설계할 때 아키텍처 패턴 선택",
      "기존 에이전트의 성능이 부족할 때 패턴 업그레이드 검토",
      "멀티에이전트 시스템을 설계할 때 조율 전략 수립",
      "에이전트 워크플로우의 복잡도와 비용의 균형 조절"
    ],
    tags: ["워크플로우 패턴", "아키텍처", "에이전트 설계", "멀티에이전트"],
    difficulty: "중급",
    toolRecommendation: "둘 다"
  },
  "https://claude.com/blog/improving-skill-creator-test-measure-and-refine-agent-skills": {
    summary: "Agent Skills를 테스트, 측정, 개선하는 방법에 대한 가이드. Skill Creator 도구의 개선 사항과 함께, 스킬 품질을 체계적으로 향상시키는 프로세스를 소개합니다.",
    keyFeatures: [
      "Skill Creator로 스킬 자동 생성 및 반복 개선",
      "스킬 성능 측정을 위한 평가 프레임워크",
      "A/B 테스트를 통한 스킬 버전 비교",
      "분산 분석(variance analysis)으로 일관성 측정"
    ],
    howToUse: "Claude Code에서 /skill-creator를 사용하여 새 스킬을 만들고, 여러 테스트 케이스로 성능을 측정합니다. 결과를 분석하여 프롬프트를 개선하고, 다시 측정하는 반복 루프를 통해 스킬 품질을 높이세요.",
    useCases: [
      "반복적으로 수행하는 작업을 재사용 가능한 스킬로 만들 때",
      "기존 스킬의 품질을 체계적으로 개선하고 싶을 때",
      "팀 전체에 공유할 표준화된 작업 프로세스를 만들 때",
      "AI 출력의 일관성을 높이고 싶을 때"
    ],
    tags: ["Skills", "평가", "품질 개선", "Skill Creator"],
    difficulty: "중급",
    toolRecommendation: "Claude"
  },
  "https://developers.openai.com/blog/skills-agents-sdk": {
    summary: "OpenAI가 Agents SDK 저장소 유지보수를 Skills와 GitHub Actions로 자동화한 사례. 3개월간 PR 병합이 44% 증가(316→457건)했으며, .agents/skills/ 폴더에 재사용 가능한 워크플로우를 정의합니다.",
    keyFeatures: [
      "Skills - 재사용 가능한 워크플로우를 .agents/skills/ 폴더에 정의",
      "AGENTS.md - 저장소 규칙을 파일로 정의하여 일관성 강제",
      "PR 병합 44% 증가 (Python: 182→226, JS: 134→231)",
      "점진적 공개 - 메타데이터로 라우팅 후 필요시 상세 지침 로드",
      "반복 작업은 스크립트화, 맥락 판단은 모델에 위임"
    ],
    howToUse: ".agents/skills/ 폴더에 SKILL.md 파일을 만들어 각 워크플로우의 이름, 설명, 단계를 정의하세요. AGENTS.md에 필수 스킬 실행 시점과 규칙을 명시합니다. GitHub Actions로 PR 생성 시 자동으로 스킬 기반 검증을 실행하도록 연동하세요.",
    useCases: [
      "오픈소스 프로젝트의 PR 리뷰/머지 자동화",
      "코드 검증, 문서 동기화 등 반복 워크플로우 정의",
      "팀 내 코딩 규칙을 AI가 강제하도록 설정",
      "새 기여자의 PR도 일관된 품질 기준을 적용"
    ],
    tags: ["Skills", "AGENTS.md", "OSS", "GitHub Actions", "자동화"],
    difficulty: "중급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/building-frontend-uis-with-codex-and-figma": {
    summary: "Codex와 Figma의 MCP 서버를 연결하여 디자인↔코드 양방향 워크플로우를 구현합니다. Figma 디자인에서 코드를 생성하거나, 작동하는 웹 앱을 몇 초 만에 Figma 프레임으로 변환할 수 있습니다.",
    keyFeatures: [
      "디자인→코드: Figma 프레임에서 레이아웃, 스타일, 컴포넌트 정보 추출 후 코드 생성",
      "코드→디자인: 웹 앱 인터페이스를 편집 가능한 Figma 프레임으로 변환",
      "MCP(Model Context Protocol) 서버 기반 통합",
      "디자인 시스템 컴포넌트 자동 적용"
    ],
    howToUse: "Codex 데스크톱 앱에서 Figma MCP 서버를 연결합니다. Figma에서 프레임 링크를 복사해 Codex에 전달하면 코드를 생성하고, 반대로 코드를 Figma 디자인으로 변환할 수도 있습니다.",
    useCases: [
      "디자이너가 만든 Figma 시안을 즉시 코드로 변환",
      "개발된 UI를 다시 Figma에서 수정하고 반복할 때",
      "디자인 시스템 컴포넌트를 코드에 일관되게 적용할 때",
      "프로토타입을 빠르게 만들어 디자인 리뷰 받을 때"
    ],
    tags: ["Figma", "MCP", "프론트엔드", "디자인 시스템", "양방향 워크플로우"],
    difficulty: "중급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/realtime-perplexity-computer": {
    summary: "Perplexity가 OpenAI Realtime API를 사용해 음성 검색 기능을 수백만 사용자에게 제공한 사례. 실시간 음성 입력으로 검색을 수행하는 경험을 구축했습니다.",
    keyFeatures: [
      "Realtime API를 활용한 실시간 음성 검색",
      "수백만 사용자 규모 서비스 구축 사례",
      "음성 입력에서 검색 결과까지 매끄러운 경험",
      "대규모 트래픽 처리를 위한 아키텍처"
    ],
    howToUse: "OpenAI Realtime API를 통해 음성 스트리밍 입력을 받고, 실시간으로 텍스트 변환 및 검색을 수행합니다. WebSocket 기반 연결로 낮은 지연시간을 달성합니다.",
    useCases: [
      "음성 기반 검색 서비스 구축",
      "실시간 음성 인터랙션이 필요한 앱",
      "핸즈프리 인터페이스가 필요한 모바일 앱",
      "대규모 사용자를 위한 실시간 API 활용 사례 참고"
    ],
    tags: ["Realtime API", "음성 검색", "Perplexity", "대규모 서비스"],
    difficulty: "고급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/designing-delightful-frontends-with-gpt-5-4": {
    summary: "GPT-5.4를 활용한 프론트엔드 디자인 생성 가이드. 더 세련되고 아름다운 UI를 생성하기 위한 프롬프팅 기법과 디자인 원칙을 다룹니다.",
    keyFeatures: [
      "GPT-5.4의 향상된 디자인 생성 능력",
      "세련된 프론트엔드 UI 자동 생성",
      "효과적인 디자인 프롬프팅 기법",
      "사용자를 기쁘게 하는 인터랙션 디자인 패턴"
    ],
    howToUse: "프론트엔드 UI를 만들 때 구체적인 디자인 방향(미니멀, 모던 등)과 사용자 경험 목표를 프롬프트에 포함하세요. 색상 팔레트, 타이포그래피, 애니메이션 등 구체적인 디자인 요소를 지정하면 더 좋은 결과를 얻습니다.",
    useCases: [
      "랜딩 페이지를 빠르게 프로토타이핑할 때",
      "디자이너 없이 세련된 UI를 만들어야 할 때",
      "다양한 디자인 시안을 빠르게 비교할 때",
      "마이크로 인터랙션과 애니메이션을 추가할 때"
    ],
    tags: ["GPT-5.4", "프론트엔드", "디자인", "UI 생성"],
    difficulty: "초급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/one-year-of-responses": {
    summary: "OpenAI Responses API 출시 1주년 회고. 프롬프트에서 제품까지의 여정을 돌아보며, API의 발전과 개발자 생태계의 성장을 다룹니다.",
    keyFeatures: [
      "Responses API 1년간의 발전 과정",
      "개발자 생태계의 성장과 활용 사례",
      "API 설계 결정의 배경과 교훈",
      "향후 발전 방향"
    ],
    howToUse: "OpenAI의 API 발전 방향을 이해하고, Responses API의 설계 철학을 참고하여 자신의 AI 제품을 설계하세요.",
    useCases: [
      "OpenAI API 기반 제품의 아키텍처 설계 시 참고",
      "AI API의 발전 트렌드를 이해할 때",
      "프롬프트 기반 프로토타입을 프로덕션 제품으로 발전시킬 때"
    ],
    tags: ["Responses API", "API 발전", "개발자 생태계"],
    difficulty: "초급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/run-long-horizon-tasks-with-codex": {
    summary: "GPT-5.3-Codex로 25시간 연속 자율 작업 실험. 빈 저장소에서 디자인 도구를 구축하여 30,000줄 코드, 13M 토큰을 사용했습니다. 내구적 메모리 구조(Prompt.md, Plan.md, Implement.md, Documentation.md)가 성공의 핵심입니다.",
    keyFeatures: [
      "25시간 연속 자율 작업으로 완전한 디자인 도구 구축",
      "30,000줄 코드 생성, 13M 토큰 사용",
      "내구적 메모리 구조 - 4개 파일로 프로젝트 상태 관리",
      "실패 자동 복구 및 마일스톤별 검증(린트, 타입체크, 테스트, 빌드)",
      "계획→편집→테스트→검토→복구→문서화 에이전트 루프"
    ],
    howToUse: "장기 작업을 시작하기 전에 Prompt.md(완료 기준), Plan.md(마일스톤), Implement.md(구현 지침), Documentation.md(상태 기록)를 준비하세요. 각 마일스톤마다 검증 단계를 넣어 품질을 보장합니다.",
    useCases: [
      "빈 저장소에서 완전한 애플리케이션을 자율적으로 구축",
      "대규모 리팩토링을 단계별로 자동 수행",
      "복잡한 프로젝트를 마일스톤 기반으로 자동 구현",
      "프로토타입에서 프로덕션까지 자율 개발"
    ],
    tags: ["장기 작업", "자율 실행", "내구적 메모리", "30K LOC", "에이전트 루프"],
    difficulty: "고급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/eval-skills": {
    summary: "Codex 에이전트 스킬을 체계적으로 테스트, 점수화, 개선하는 6단계 평가(Evals) 프레임워크. '좋아 보인다'는 주관적 판단 대신 측정 가능한 기준으로 스킬 품질을 관리합니다.",
    keyFeatures: [
      "6단계 체계적 평가 프로세스",
      "4가지 성공 기준 - 결과, 프로세스, 스타일, 효율성",
      "codex exec --json으로 결정론적 검사",
      "--output-schema로 모델 기반 자동 점수화",
      "10-20개 테스트 케이스로 회귀 방지"
    ],
    howToUse: "1)성공 기준 정의 → 2)SKILL.md 작성 → 3)수동 테스트 → 4)10-20개 프롬프트 세트 작성 → 5)codex exec --json으로 결정론적 검사 → 6)--output-schema로 모델 평가. 이 루프를 반복하여 스킬을 개선하세요.",
    useCases: [
      "AI 스킬의 품질을 객관적으로 측정하고 싶을 때",
      "스킬 변경 후 성능 저하(regression)를 감지할 때",
      "팀 내 여러 사람이 만든 스킬의 품질을 표준화할 때",
      "AI 출력의 일관성과 정확도를 지속적으로 개선할 때"
    ],
    tags: ["Evals", "스킬 평가", "품질 관리", "측정", "테스트"],
    difficulty: "중급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/skyscanner-codex-jetbrains-mcp": {
    summary: "Skyscanner가 Codex CLI를 JetBrains IDE에 MCP(Model Context Protocol)로 통합한 사례. 디버깅, 테스트, 개발 워크플로우를 IDE 내에서 AI로 가속화합니다.",
    keyFeatures: [
      "JetBrains IDE에서 직접 Codex CLI 사용",
      "MCP(Model Context Protocol) 기반 통합",
      "디버깅, 테스트, 개발 워크플로우 가속화",
      "엔터프라이즈 개발 환경에서의 실전 도입 사례"
    ],
    howToUse: "JetBrains IDE에 MCP 서버를 설정하고 Codex CLI를 연결합니다. IDE 내에서 코드 컨텍스트를 자동으로 전달하여, AI가 현재 작업 중인 코드를 이해하고 도움을 줍니다.",
    useCases: [
      "JetBrains IDE(IntelliJ, WebStorm 등)에서 AI 코딩 지원을 받고 싶을 때",
      "기존 IDE 워크플로우를 깨지 않으면서 AI를 도입할 때",
      "엔터프라이즈 환경에서 AI 코딩 도구를 표준화할 때",
      "디버깅과 테스트 작성을 IDE 내에서 AI로 처리할 때"
    ],
    tags: ["JetBrains", "MCP", "IDE 통합", "Skyscanner", "엔터프라이즈"],
    difficulty: "중급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/codex-for-documentation-dagster": {
    summary: "Dagster Labs가 오픈소스 프로젝트에서 Codex를 활용해 문서화와 콘텐츠 번역을 가속화한 사례. 문서 완성도를 측정하고, 여러 형태로 콘텐츠를 변환하는 워크플로우를 구축했습니다.",
    keyFeatures: [
      "문서화 가속화 - 기존 코드에서 문서 자동 생성",
      "콘텐츠 번역 및 다양한 형태로 변환",
      "문서 완성도(completeness) 측정 방법론",
      "오픈소스 프로젝트에서의 실전 활용"
    ],
    howToUse: "Codex에 코드와 기존 문서를 입력으로 주고, 누락된 문서를 생성하거나 기존 문서를 다른 형태(튜토리얼, API 레퍼런스 등)로 변환하세요. 문서 완성도를 정량적으로 측정하여 개선 포인트를 파악합니다.",
    useCases: [
      "오픈소스 프로젝트의 문서를 체계적으로 관리할 때",
      "API 레퍼런스, 튜토리얼, 가이드 등 다양한 문서 형태가 필요할 때",
      "다국어 문서를 만들어야 할 때",
      "문서화 수준을 정량적으로 측정하고 개선할 때"
    ],
    tags: ["문서화", "오픈소스", "Dagster", "콘텐츠 변환"],
    difficulty: "초급",
    toolRecommendation: "Codex"
  },
  "https://developers.openai.com/blog/codex-at-devday": {
    summary: "OpenAI DevDay 2025에서 Codex가 활용된 방식. 행사 경험, 데모, 제품 개발에 Codex가 직접 투입되어, AI 도구가 실제 이벤트 운영에 어떻게 기여하는지 보여줍니다.",
    keyFeatures: [
      "DevDay 2025 행사 운영에 Codex 직접 활용",
      "라이브 데모 및 제품 개발 지원",
      "이벤트 경험 설계에 AI 도구 활용",
      "실제 이벤트에서의 AI 실전 적용 사례"
    ],
    howToUse: "행사나 데모 준비 시 Codex를 활용해 프로토타입을 빠르게 만들고, 라이브 코딩 데모를 준비할 수 있습니다.",
    useCases: [
      "테크 이벤트의 라이브 데모 준비",
      "해커톤에서 빠른 프로토타이핑",
      "행사용 인터랙티브 경험 구축",
      "제품 데모를 위한 샘플 앱 빠르게 생성"
    ],
    tags: ["DevDay", "이벤트", "데모", "프로토타이핑"],
    difficulty: "초급",
    toolRecommendation: "Codex"
  }
};

function apply() {
  const data = JSON.parse(fs.readFileSync(DATA_PATH, "utf-8"));

  let updated = 0;
  for (const article of data.articles) {
    const analysis = analyses[article.url];
    if (analysis) {
      article.analysis = analysis;
      article.analyzed = true;
      article.analyzedAt = new Date().toISOString();
      // Clean title - remove "| Claude" or "| OpenAI Developers" suffix
      article.title = article.title
        .replace(/\s*\|\s*Claude$/, "")
        .replace(/\s*\|\s*OpenAI Developers$/, "");
      updated++;
    }
  }

  data.lastUpdated = new Date().toISOString();
  fs.writeFileSync(DATA_PATH, JSON.stringify(data, null, 2));
  console.log(`Updated ${updated} articles with analysis data.`);
}

apply();
